<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-07-25 08:38

=======
# Generated by Django 5.0.7 on 2024-07-29 10:41

import django.db.models.deletion
from django.conf import settings
>>>>>>> d6968ac (Modified Story model to include comments and likes relationships and defined the views and form)
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> d6968ac (Modified Story model to include comments and likes relationships and defined the views and form)
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='story',
            name='img_title',
        ),
        migrations.RemoveField(
            model_name='story',
            name='snip',
        ),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=200),
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.story')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.story')),
            ],
        ),
>>>>>>> d6968ac (Modified Story model to include comments and likes relationships and defined the views and form)
    ]
